language: d
script: ./travis.sh

addons:
  apt:
    packages:
      - libcairo2-dev
      - libglib2.0-dev
      - libgnomeui-dev
      - libgtk2.0-dev
      - libpango1.0-dev
      - libxcomposite-dev
      - libxcursor-dev
      - libxdamage-dev
      - libxfixes-dev
      - libxi-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxtst-dev

d:
  - dmd-2.067.0
  - dmd-2.066.1
  - dmd-2.065.0

